prefix c14n: <http://www.topbraid.org/c14n#> 
prefix dash: <http://datashapes.org/dash#> 
prefix sh: <http://www.w3.org/ns/shacl#> 
prefix shskos: <http://topbraid.org/shacl/skos.shacl#> 
prefix message: <http://www.w3.org/ns/shacl#message>
 SELECT ?focusNode ?message ?severity ?shape ?resultPath WHERE 
 { 
 	?vr a sh:ValidationResult . 
 	?vr sh:focusNode ?focusNode . 
 	OPTIONAL { 
 		?vr sh:resultMessage ?message . 
 		?vr sh:resultPath ?resultPath . 
 		?vr sh:sourceShape ?shape . 
 		?vr sh:resultSeverity ?severity .
 	}
 }ORDER BY ?severity ?message
